[project]
name = "sol"
version = "0.1.0"
description = "Sol Game Engine"
readme = "README.md"
authors = [
    { name = "TripleBites", email = "TripleBites@proton.me" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
sol = "sol:main"

[tool.maturin]
module-name = "sol._core"
python-packages = ["sol"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "maturin>=1.14.1",
    "maturin-import-hook>=0.3.0",
    "pytest>=9.1.1",
]
